#pragma once

#include <string>

using namespace std;

struct RGB {
	int R, G, B;

	RGB& operator=(const RGB& rhs) {
		R = rhs.R;
		G = rhs.G;
		B = rhs.B;
		return *this;
	}
};

class Image {
public:
	Image(string strFile);
	Image(const Image* im); //copy constructor for editor to load onto undoStack
	~Image();

	string getName();
	int getNumCol();
	int getNumRow();
	RGB** getRGBArray();
	void setRGBArray(RGB** newArray);

	friend bool operator==(const Image& lhs, const Image& rhs); //doesnt use pointers!

	//testing methods
	void print(int row, int col);

	void writeFile(string strFile); //implement filepath generated by string + num?

private:
	int numCol, numRow;
	string name;
	RGB** rgbArray;
};