#pragma once

#include <string>

using namespace std;

struct RGB {
	unsigned char R, G, B; //store as unsigned char instead of int to save memory, also for fltk image constructor

	RGB& operator=(const RGB& rhs) {
		R = rhs.R;
		G = rhs.G;
		B = rhs.B;
		return *this;
	}
};

class Image { //a basic image object
public:
	Image(const string &filePath);
	Image(Image* im); //copy constructor for Command to push onto undoStack
	~Image();

	string getName();
	int getNumCol();
	int getNumRow();
	RGB** getRGBArray();
	void setRGBArray(RGB** newArray);

	friend bool operator==(const Image& lhs, const Image& rhs); //doesnt use pointers!
	void writeFile(const string &filePath); //implement filepath automatically generated by string + num?

private:
	int mNumCol, mNumRow;
	string mImageName;
	RGB** mRGBArray;
};